services:
  database:
    image: postgres:15-alpine
    container_name: postgres_db_travelar
    restart: unless-stopped
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: travelar_pass
      POSTGRES_DB: travelar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d travelar"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
       - travelar_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_travelar
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-travelar_pass}
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    networks:
       - travelar_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelar_app
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=developer
      - DB_PASSWORD=travelar_pass
      - DB_DATABASE=travelar
      - JWT_SECRET=${JWT_SECRET:-SUPER_SECRETO_PARA_JWT}
      - DB_SSL=false 
      - NODE_ENV=development
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
       - travelar_network

networks:
  travelar_network:
    driver: bridge

volumes:
  postgres_data: